wdir: null
seed: 111

original_data:
  lower_case_col_names: true
  ignore_header: null
  ignore_cols: null
  delimiter: ',' 
  id_column: id
  train_file:
    path: # absolute path to csv file with independant and dependant variables
    target_col: sales
    kfold_col: kfold
    kfold: 10 
    stratified: true
    n_bins: auto
    shuffle: true
    output_dir: original_data/kfold/
  test_file:
    path: # absolute path to csv file with independant and dependant variables

featurize: # todo

train: # todo (includes path to model hyperparameters)

inference: # todo